wandb_version: 1

LEARNING_RATE:
  desc: null
  value: 0.008401001072586628
N_EPOCHS:
  desc: null
  value: 5
BATCH_SIZE:
  desc: null
  value: 128
DROPOUT_RATE:
  desc: null
  value: 0.23384906013439496
IM_SIZE:
  desc: null
  value: 224
REGULARIZATION_RATE:
  desc: null
  value: 0.06037504500103182
N_FILTERS:
  desc: null
  value: 6
KERNEL_SIZE:
  desc: null
  value: 3
N_STRIDES:
  desc: null
  value: 1
POOL_SIZE:
  desc: null
  value: 2
N_DENSE_1:
  desc: null
  value: 32
N_DENSE_2:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710020074.677
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.4
      5: 0.16.3
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
