wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710020735.300202
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      3:
      - 23
      - 35
      - 37
      4: 3.11.4
      5: 0.16.3
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
DROPOUT_RATE:
  desc: null
  value: 0.16980879980747154
LEARNING_RATE:
  desc: null
  value: 0.006563057695496103
N_DENSE_1:
  desc: null
  value: 16
N_DENSE_2:
  desc: null
  value: 64
REGULARIZATION_RATE:
  desc: null
  value: 0.05403028244922495
